// <auto-generated />
using System;
using IoTSpy.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoTSpy.Storage.Migrations
{
    [DbContext(typeof(IoTSpyDbContext))]
    [Migration("20260309120000_AddPacketCapture")]
    partial class AddPacketCapture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");
            // Full snapshot not required for migration application
#pragma warning restore 612, 618
        }
    }
}
