// <auto-generated />
using System;
using IoTSpy.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoTSpy.Storage.Migrations
{
    [DbContext(typeof(IoTSpyDbContext))]
    [Migration("20260304120000_AddPhase3Scanner")]
    partial class AddPhase3Scanner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("IoTSpy.Core.Models.CapturedRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsModified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestBodySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestHeaders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseBodySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseHeaders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TlsCipherSuite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Host");

                    b.HasIndex("Timestamp");

                    b.ToTable("Captures");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.CertificateEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRootCa")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NotAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NotBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKeyPem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectAltNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonName");

                    b.HasIndex("IsRootCa");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InterceptionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.HasIndex("MacAddress");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ProxySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CaptureRequestBodies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CaptureResponseBodies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CaptureTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatewayIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListenAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBodySizeKb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NetworkInterface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProxyPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetDeviceIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransparentProxyPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProxySettings");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Banner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("CveId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CvssScore")
                        .HasColumnType("REAL");

                    b.Property<string>("CveDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<long>("FoundAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId");

                    b.HasIndex("Type");

                    b.HasIndex("Severity");

                    b.ToTable("ScanFindings");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableFingerprinting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableCredentialTest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableCveLookup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableConfigAudit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFindings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Status");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.CapturedRequest", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.Device", "Device")
                        .WithMany("Captures")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanFinding", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.ScanJob", "ScanJob")
                        .WithMany("Findings")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanJob", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.Device", b =>
                {
                    b.Navigation("Captures");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanJob", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
