// <auto-generated />
using System;
using IoTSpy.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoTSpy.Storage.Migrations
{
    [DbContext(typeof(IoTSpyDbContext))]
    [Migration("20260325130000_AddApiSpecAndContentReplacement")]
    partial class AddApiSpecAndContentReplacement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            // This migration adds ApiSpecDocuments and ContentReplacementRules tables.
            // Full model is in IoTSpyDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
