// <auto-generated />
using IoTSpy.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoTSpy.Storage.Migrations
{
    [DbContext(typeof(IoTSpyDbContext))]
    [Migration("20260326120000_AddProxyAutoStart")]
    partial class AddProxyAutoStart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");
            // Full model snapshot is in IoTSpyDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
