// <auto-generated />
using System;
using IoTSpy.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoTSpy.Storage.Migrations
{
    [DbContext(typeof(IoTSpyDbContext))]
    partial class IoTSpyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("IoTSpy.Core.Models.ApiSpecDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MockEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenApiJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PassthroughFirst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseLlmAnalysis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Host");

                    b.HasIndex("Status");

                    b.ToTable("ApiSpecDocuments");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.Breakpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostPattern")
                        .HasColumnType("TEXT");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathPattern")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScriptCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.ToTable("Breakpoints");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.CaptureDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanCapture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsPromiscuousMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("MacAddress");

                    b.ToTable("CaptureDevices");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.CapturedPacket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArpOperation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArpSenderMac")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArpTargetIp")
                        .HasColumnType("TEXT");

                    b.Property<long>("CaptureIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationMac")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DestinationPort")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DnsQueryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DnsResponseType")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrameNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HttpMethodName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpRequestUri")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpResponseCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFragment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetransmission")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layer2Protocol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Layer3Protocol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Layer4Protocol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadPreview")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMac")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourcePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspicionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("TcpFlags")
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeDeltaFromPrevious")
                        .HasColumnType("REAL");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UdpLength")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationIp");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Protocol");

                    b.HasIndex("SourceIp");

                    b.HasIndex("Timestamp");

                    b.ToTable("Packets");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.CapturedRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsModified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestBodySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestHeaders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseBodySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseHeaders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TlsCipherSuite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Host");

                    b.HasIndex("Timestamp");

                    b.ToTable("Captures");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.CertificateEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRootCa")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NotAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NotBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKeyPem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectAltNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonName");

                    b.HasIndex("IsRootCa");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ContentReplacementRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ApiSpecDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathPattern")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacementContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacementFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacementValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiSpecDocumentId");

                    b.HasIndex("Priority");

                    b.ToTable("ContentReplacementRules");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InterceptionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.HasIndex("MacAddress");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.FuzzerJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Anomalies")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BaseCaptureId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedMutations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConcurrentRequests")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("MutationCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strategy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCaptureId");

                    b.HasIndex("Status");

                    b.ToTable("FuzzerJobs");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.FuzzerResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnomalyReason")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FuzzerJobId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MutatedBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MutationDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MutationIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FuzzerJobId");

                    b.HasIndex("IsAnomaly");

                    b.ToTable("FuzzerResults");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ManipulationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyReplace")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyReplaceWith")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeaderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OverrideStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathPattern")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("Priority");

                    b.ToTable("ManipulationRules");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.OpenRtbEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BidCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CapturedRequestId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDeviceInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasGeoData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasUserData")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImpressionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatBids")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapturedRequestId");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("Exchange");

                    b.HasIndex("MessageType");

                    b.ToTable("OpenRtbEvents");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.OpenRtbPiiPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostPattern")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strategy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("Priority");

                    b.ToTable("OpenRtbPiiPolicies");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.PiiStrippingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CapturedRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalValueHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RedactedPreview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Strategy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StrippedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CapturedRequestId");

                    b.HasIndex("FieldPath");

                    b.HasIndex("Host");

                    b.HasIndex("StrippedAt");

                    b.ToTable("PiiStrippingLogs");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ProxySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CaptureRequestBodies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CaptureResponseBodies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CaptureTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatewayIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListenAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBodySizeKb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NetworkInterface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProxyPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SslStrip")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetDeviceIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransparentProxyPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProxySettings");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ReplaySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OriginalCaptureId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeaders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestScheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHeaders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OriginalCaptureId");

                    b.ToTable("ReplaySessions");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Banner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpe")
                        .HasColumnType("TEXT");

                    b.Property<string>("CveDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CveId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CvssScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FoundAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId");

                    b.HasIndex("Severity");

                    b.HasIndex("Type");

                    b.ToTable("ScanFindings");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableConfigAudit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableCredentialTest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableCveLookup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableFingerprinting")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFindings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Status");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScheduledScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastRunAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LastScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextRunAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IsEnabled");

                    b.ToTable("ScheduledScans");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("Action");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.DashboardLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DashboardLayouts");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ContentReplacementRule", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.ApiSpecDocument", "ApiSpecDocument")
                        .WithMany("ReplacementRules")
                        .HasForeignKey("ApiSpecDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiSpecDocument");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.CapturedPacket", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.CaptureDevice", "Device")
                        .WithMany("Packets")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.CapturedRequest", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.Device", "Device")
                        .WithMany("Captures")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.FuzzerJob", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.CapturedRequest", "BaseCapture")
                        .WithMany()
                        .HasForeignKey("BaseCaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseCapture");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.FuzzerResult", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.FuzzerJob", "FuzzerJob")
                        .WithMany("Results")
                        .HasForeignKey("FuzzerJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuzzerJob");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ReplaySession", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.CapturedRequest", "OriginalCapture")
                        .WithMany()
                        .HasForeignKey("OriginalCaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalCapture");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanFinding", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.ScanJob", "ScanJob")
                        .WithMany("Findings")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanJob", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScheduledScan", b =>
                {
                    b.HasOne("IoTSpy.Core.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ApiSpecDocument", b =>
                {
                    b.Navigation("ReplacementRules");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.CaptureDevice", b =>
                {
                    b.Navigation("Packets");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.Device", b =>
                {
                    b.Navigation("Captures");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.FuzzerJob", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("IoTSpy.Core.Models.ScanJob", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
