{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iotspy.fullname" . }}-secret
  labels:
    {{- include "iotspy.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ required "auth.jwtSecret is required" .Values.auth.jwtSecret | b64enc | quote }}
{{- end }}
