apiVersion: v1
kind: Service
metadata:
  name: {{ include "iotspy.fullname" . }}
  labels:
    {{- include "iotspy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "iotspy.selectorLabels" . | nindent 4 }}
